### PR TITLE
 #79 add extra json fields to the structure and allow marshalling

### PR DESCRIPTION
**Pull request by smirnov**
Adding extra structure to tokeninfo response with plain marshaling (key = value in the response body).

### CODE REVIEW

**Comment by lmineiro** [comment]
Are these just custom Claims?

**Comment by vroldanbet** [comment]
@lmineiro essentially yes: we want to mock some claims to guarantee backward compatibility of our legacy tokeninfo system. Would you prefer to see it named "PrivateClaims"?

**Comment by smirnov** [comment]
@lmineiro  this is extra arbitrary metadata bucket, that allows injecting extra fields by extending/replacing jwt processor to use non-generic logic. (for example - imitating responses from other, not-so-standard-concious solutions, that used to mix identity and authorization in one go in the token info.
This should not affect tokeninfo in any way and is not required for planb, but is needed to enable extension for other usecases.

**Comment by vroldanbet** [comment]
@smirnov please provide tests for this new functionality

**Comment by lmineiro** [comment]
@smirnov your proposed implementation and explanation seem to point exactly into private claims. If we can't be sure there won't be a clash with the registered/public ones, this would follow the standard

**Comment by smirnov** [comment]
@lmineiro yes, I can rename that in the code. As for validation of claim clashing - since the extension requires and conscious decision of a developer, implementing a new jwtprocessor class, I would say that it makes more sense to keep the sanity check on the side of the developer, so that it is done once during design phase and not every time in runtime.

The claims have to be put in the map by JWT processor explicitly, they are not automatically taken from anywhere in the JWT, that is incoming into the system.

**Comment by vroldanbet** [comment]
:+1:

**Comment by lmineiro** [comment]
👍

**Pull request merged**
